### ISSUE TITLE
Fix UI to display message on error and aggregator to return error

### ISSUE THREAD

**Issue by blankdots** [CSCfi/beacon-openshift#22]
#### Describe the bug
When the beacon does not return anything

#### To Reproduce
Steps to reproduce the behaviour:
1. simulate a beacon-python returns `504`, or do a query that does not return anything
2. aggregator returns `200` and `[` as the response
3. Beacon-ui does not display anything

#### Expected behavior
Message that tells the user that something weird has happened.

**Comment by teemukataja** [comment]
This is caused by beacon-aggregator's `StreamResponse`. Check into changing this to synchronous `Response` or `aio websocket`, because we handle this stream synchronously in the UI anyway.

**Comment by blankdots** [comment]
webSockets option sounds better (new issue if we are going to do the simple solution now), but maybe a simple parse of the response on the UI side to see if it has data + the keys we need would be sufficient for now.

**Comment by blankdots** [comment]
maybe related to this: we would like to render the responses in the UI asynchronously as well, whenever we get hits (or not) display them, don't wait for all beacons to respond. but still display the spinner while we wait the response from other beacons
